import Navbar from "@/components/Navbar";
import "./globals.css";
import { StoreProvider } from "@/store/StoreProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <Navbar />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
